apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-thanosql.fullname" . }}-lab
  labels:
    {{- include "aws-thanosql.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.jupyterlab.configmap.data | nindent 4 }}