apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aws-thanosql.fullname" . }}-claim
  labels:
    {{- include "aws-thanosql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: {{ .Values.storageClass }}