apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-thanosql.fullname" . }}-engine
  labels:
    {{- include "aws-thanosql.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.engine.configmap.data | nindent 4 }}