apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-thanosql.fullname" . }}-engine
  labels:
    {{- include "aws-thanosql.labels" . | nindent 4 }}
    app.name: {{ include "aws-thanosql.fullname" . }}-engine
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: pg
  selector:
    {{- include "aws-thanosql.selectorLabels" . | nindent 4 }}
    app.name: {{ include "aws-thanosql.fullname" . }}-engine
    
