apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanosql-engine.fullname" . }}
  labels:
    {{- include "thanosql-engine.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 4 }}